"""empty message

Revision ID: 369a321b1db0
Revises: e1f684145c6e
Create Date: 2026-07-22 23:46:09.760165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369a321b1db0'
down_revision = 'e1f684145c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('date_expirate',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.alter_column('date_expirate',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
