"""empty message

Revision ID: e1f684145c6e
Revises: 
Create Date: 2026-07-22 23:28:03.010170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f684145c6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('url',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('nb_click', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_expirate', sa.DateTime(), nullable=False),
    sa.Column('id_author', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id_author'], ['user.id'], name=op.f('fk_url_id_author_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_url'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    op.drop_table('user')
    # ### end Alembic commands ###
